name: PowerShell Module Deployment

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**

jobs:
  validation:
    name: Validate Module
    uses: ./.github/workflows/validate-wf.yml
    permissions:
      checks: write
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: validation
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Version Check
        shell: pwsh
        run: |
          $moduleName = (Get-Item -Path .).Name
          $moduleManifestData = Import-PowerShellDataFile -Path ("./src/{0}.psd1" -f $moduleName)
          $moduleManifestVersion = $moduleManifestData.ModuleVersion -as [System.Version]
          $psGalleryModule = Find-Module -Name $moduleName -ErrorAction SilentlyContinue
          if ($psGalleryModule) {
            if ([System.Version]$psGalleryModule.Version -le [System.Version]$moduleManifestVersion.Version) {
              throw "Version hasn't been updated.  Ensure version is h"
            }
          } else { 
              ("No existing module found on PSGallery: {0}" -f $moduleName)          
          }

      - name: Extract Repo Name
        id: repo_name
        run: | 
          echo "repo_name=$(echo '${{ github.repository }}' | cut -d '/' -f 2)" >> $GITHUB_OUTPUT
          echo ${{ steps.repo_name.outputs.repo_name }}
          
      - name: Rename 'src' to Module Name
        shell: pwsh
        run: |
          Rename-Item -Path ./src/ -NewName ${{ steps.repo_name.outputs.repo_name }} -Force
          
      - name: Publish PowerShell
        uses: natescherer/publish-powershell-action@v1.1.1
        with:
          token: ${{ secrets.PSGallery }}
          target: gallery
          path: ${{ steps.repo_name.outputs.repo_name }}/
