name: PowerShell Module Validation

on:
  pull_request:
    branches:
      - main
    types: [opened, edited, review_requested]
  push:
    branches-ignore:
      - 'main'
    paths-ignore:
      - .github/**
  workflow_dispatch:
    
jobs:
  validation:
    name: Validate Module
    uses: ./.github/workflows/validate-wf.yml
